---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.11.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.11.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.11.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html[Cloud Manager Release Notes^] for details.

== 9.11.1 RC1 (8 June 2022)

Cloud Volumes ONTAP 9.11.1 Release Candidate 1 is now available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== Performance enhancement

We have enhanced the read performance of new aggregates created in 9.11.1 or later.

=== Increased storage efficiency

Starting with the 9.11.1 release, all new volumes enabled for storage efficiency will include a new compression feature called temperature-sensitive storage efficiency. The previous generation compression feature is no longer used.

Temperature-sensitive storage efficiency compresses data based on data temperature, or how often the data is used. Cold data, or data that is not used often, is recompressed with a higher compression ratio for increased storage efficiency.

=== Support for 24 storage VMs in Google Cloud

24 storage VMs are now supported with Cloud Volumes ONTAP in Google Cloud for most configurations.

link:reference-limits-azure.html#storage-vm-limits[Learn more about storage VM limits in Google Cloud].

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html[Learn how to create data-serving storage VMs for Cloud Volumes ONTAP in Google Cloud^]

=== VPC sharing in AWS

Cloud Volumes ONTAP HA pairs are supported in AWS with VPC sharing. VPC sharing enables your organization to share subnets with other AWS accounts. Networking (the VPC, subnets, and route tables) reside in the VPC owner account, while the EC2 instances for the HA configuration reside in a participant account using shared subnets.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploy-aws-shared-vpc.html[Learn how to deploy an HA pair in a shared subnet^]

== New unsupported ONTAP feature

Multi-admin verification is not supported with Cloud Volumes ONTAP. Enabling multi-admin verification on Cloud Volumes ONTAP will result in an unsupported configuration.

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when Cloud Manager notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.11.1 from the 9.11.0 release. Cloud Manager will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

=== Required version of the Connector

The Cloud Manager Connector must be running version 3.9.19 or later to deploy new Cloud Volumes ONTAP 9.11.1 systems and to upgrade existing systems to 9.11.1.

TIP: Automatic upgrades of the Connector are enabled by default so you should be running the latest version.

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instance types

Starting with the 9.8 release, c4, m4, and r4 instance types aren't supported with new Cloud Volumes ONTAP systems. If you have an existing Cloud Volumes ONTAP system that's running on a c4, m4, or r4 instance type, you can still upgrade to this release.

We recommend changing to an instance type in the c5, m5, or r5 instance family.
