---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.11.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.11.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.11.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP (formerly Cloud Manager). See the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== 9.12.1 RC1 (15 November 2022)
Cloud Volumes ONTAP 9.12.1 Release Candidate 1 is now available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== ONTAP S3 license in GCP

An ONTAP S3 license is now included on new and existing Cloud Volumes ONTAP systems running version 9.12.1 or later in Google Cloud Platform.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html[Learn how to configure and manage S3 object storage services in ONTAP^]

=== NVMe-TCP support in Cloud Volumes ONTAP

NVMe-TCP is supported for AWS, Azure, and GCP cloud providers if you are using Cloud Volumes ONTAP version 9.12.1 or newer. Configuration and workflows for NVMe-TCP are performed exclusively through ONTAP. For more information on NVMe compatibility with ONTAP, see https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html#namespace-limitations-and-support[NVMe support and limitations^].

=== Azure HA Multiple Availability Zones 
You can now deploy a Cloud Volumes ONTAP HA configuration using Azure multiple availability zones within a region. The new configuration protects against data center failure and maintains application availability with the use of Azure zone-redundant storage (ZRS) managed disks. 

For more information about the HA configuration architecture and components, see link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html[High-availability pairs in Azure^]. 

To use this new configuration, see link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html[Launching a Cloud Volumes ONTAP HA pair in Azure]^.

== c4, m4, and r4 instances no longer supported (28 October 2022)

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that’s running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family.
 
link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 


== 9.11.1 P3 (19 October 2022)
The 9.11.1 P3 patch is now available for Cloud Volumes ONTAP for all cloud providers if you have a Connector running version 3.9.22 or later. BlueXP will prompt you to upgrade your existing systems to this patch release.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.11.1P3[View the list of bugs fixed in the P3 patch^] (NetApp Support Site login required).

== 9.11.1 GA (1 Aug 2022)

The General Availability (GA) release of Cloud Volumes ONTAP 9.11.1 is now available. The GA release includes bug fixes.

== 9.11.1 RC1 (7 June 2022)

Cloud Volumes ONTAP 9.11.1 Release Candidate 1 is now available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== Performance enhancement

We have enhanced the read performance of new aggregates created in 9.11.1 or later.

=== Increased storage efficiency

Starting with the 9.11.1 release, all new volumes enabled for storage efficiency will include a new compression feature called temperature-sensitive storage efficiency. The previous generation compression feature is no longer used.

Temperature-sensitive storage efficiency compresses data based on data temperature, or how often the data is used. Cold data, or data that is not used often, is recompressed with a higher compression ratio for increased storage efficiency.

=== VPC sharing in AWS

Cloud Volumes ONTAP HA pairs are now supported in AWS with VPC sharing. VPC sharing enables your organization to share subnets with other AWS accounts. Networking (the VPC, subnets, and route tables) reside in the VPC owner account, while the EC2 instances for the HA configuration reside in a participant account using shared subnets.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploy-aws-shared-vpc.html[Learn how to deploy an HA pair in a shared subnet^]

=== New AWS region support

Cloud Volumes ONTAP is now supported in the AWS Jakarta region (ap-southeast-3).

https://cloud.netapp.com/cloud-volumes-global-regions[View the full list of supported regions for Cloud Volumes ONTAP^]

=== New Azure region support

Cloud Volumes ONTAP is now supported in the Azure Brazil Southeast region.

https://cloud.netapp.com/cloud-volumes-global-regions[View the full list of supported regions for Cloud Volumes ONTAP^]

=== Support for 24 storage VMs in Google Cloud

24 storage VMs are now supported with Cloud Volumes ONTAP in Google Cloud for most configurations.

* link:reference-limits-gcp.html#storage-vm-limits[Learn more about storage VM limits in Google Cloud]

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html[Learn how to create data-serving storage VMs for Cloud Volumes ONTAP in Google Cloud^]

=== New Google Cloud region support

Cloud Volumes ONTAP HA pairs are now supported in the Milan (europe-west8) region.

https://cloud.netapp.com/cloud-volumes-global-regions[View the full list of supported regions for Cloud Volumes ONTAP^]

=== Modifying LIF services for new storage VMs

Starting with this release, if you create a new storage VM on a Cloud Volumes ONTAP HA pair in AWS or Azure, then you need to modify the network service policies for the storage VM. Modifying the services is required because it ensures that Cloud Volumes ONTAP can use the iSCSI LIF for outbound management connections.

Note that modifying LIF services is not required for Cloud Volumes ONTAP in Google Cloud because the BlueXP API sets the LIF services for you during creation.

The commands that you need to run are specified on the following pages:

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-aws.html[Learn how to create additional storage VMs in AWS^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html[Learn how to create additional storage VMs in Azure^]

== New unsupported ONTAP feature

The new multi-admin verification feature introduced in ONTAP 9.11.1 is not supported with Cloud Volumes ONTAP. Enabling multi-admin verification on Cloud Volumes ONTAP will result in an unsupported configuration.

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.11.1 from the 9.11.0 release and from the 9.10.1 release. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

=== Required version of the Connector

The BlueXP Connector must be running version 3.9.19 or later to deploy new Cloud Volumes ONTAP 9.11.1 systems and to upgrade existing systems to 9.11.1.

TIP: Automatic upgrades of the Connector are enabled by default so you should be running the latest version.

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.
