---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.12.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.13.0
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.13.0 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP (formerly Cloud Manager). See the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== 9.13.0 GA (5 March 2023)
The General Availability (GA) release of Cloud Volumes ONTAP 9.13.0 is now available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== Flash Cache and high write speed in Google Cloud
Support for Flash Cache, high write speed, and a high maximum transmission unit (MTU) of 8,896 bytes is now available for select instances with the Cloud Volumes ONTAP 9.13.0 release. 

Learn more about link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html[supported configurations by license for Google Cloud^].

=== Image verification in Google Cloud
Enhanced security features are now available for verifying signatures of Cloud Volumes ONTAP image files exported through Google Cloud. 

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-gcp-image-verification.html[Learn more about Google Cloud Image Verification^].

=== New instance support in Google Cloud
Freemium, PAYGO Premium, node-based BYOL, and capacity-based licenses now support two new instance types for Cloud Volumes ONTAP single node and high-availability deployments in Google Cloud. 

* n2-standard-48
* n2-standard-64

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html[Learn more about supported configurations in Google Cloud^]. 

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.13.0 from the 9.12.1 release. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

=== Required version of the Connector

The BlueXP Connector must be running version 3.9.26 or later to deploy new Cloud Volumes ONTAP 9.13.0 systems and to upgrade existing systems to 9.13.0.

TIP: Automatic upgrades of the Connector are enabled by default so you should be running the latest version.

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instances no longer supported

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that's running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family. You can't upgrade to this release until you change the instance type.
 
link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 
