---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.12.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.12.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.12.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP (formerly Cloud Manager). See the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== 9.12.1 RC1 (27 November 2022)
Cloud Volumes ONTAP 9.12.1 Release Candidate 1 is now available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== ONTAP S3 license in GCP

An ONTAP S3 license is now included on new and existing Cloud Volumes ONTAP systems running version 9.12.1 or later in Google Cloud Platform.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html[Learn how to configure and manage S3 object storage services in ONTAP^]

=== NVMe-TCP support in Cloud Volumes ONTAP

NVMe-TCP is supported for AWS, Azure, and GCP cloud providers if you are using Cloud Volumes ONTAP version 9.12.1 or newer. Configuration and workflows for NVMe-TCP are performed exclusively through ONTAP. For more information on NVMe compatibility with ONTAP, see https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html#namespace-limitations-and-support[NVMe support and limitations^].

=== Azure HA Multiple Availability Zones 
You can now deploy a Cloud Volumes ONTAP HA configuration using Azure multiple availability zones within a region. The new configuration protects against data center failure and maintains application availability with the use of Azure zone-redundant storage (ZRS) managed disks. 

For more information about the HA configuration architecture and components, see link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html[High-availability pairs in Azure^]. 

To use this new configuration, see link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html[Launching a Cloud Volumes ONTAP HA pair in Azure]^.

== c4, m4, and r4 instances no longer supported (28 October 2022)

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that’s running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family.
 
link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 
