---
sidebar: sidebar
permalink: reference-limits-azure.html
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks
summary: Cloud Volumes ONTAP has storage configuration limits in Azure to provide reliable operations. For best performance, do not configure your system at the maximum values.
---

= Storage limits in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.

== Maximum system capacity by license

The maximum system capacity for a Cloud Volumes ONTAP system is determined by its license. The maximum system capacity includes disk-based storage plus object storage used for data tiering.

NetApp doesn't support exceeding the system capacity limit. If you reach the licensed capacity limit, Cloud Manager displays an action required message and no longer allows you to add additional disks.

[cols="25,75",width=65%,options="header"]
|===
| License
| Maximum system capacity (disks + object storage)

| Freemium | 500 GiB
| PAYGO Explore	| 2 TiB (data tiering is not supported with Explore)
| PAYGO Standard | 10 TiB
| PAYGO Premium | 368 TiB
| Node-based license | 368 TiB per license
| Capacity-based license | 2 PiB

|===

===== For HA, is the license capacity limit per node or for the entire HA pair?

The capacity limit is for the entire HA pair. It is not per node. For example, if you use the Premium license, you can have up to 368 TiB of capacity between both nodes.

== Disk and tiering limits by VM size

The disk limits below are specific to disks that contain user data. The limits do not include the root disk, core disk, and VNVRAM.

The tables below show the maximum system capacity by VM size with disks alone, and with disks and cold data tiering to object storage.

* Single node systems can use Standard HDD Managed Disks, Standard SSD Managed Disks, and Premium SSD Managed Disks, with up to 32 TiB per disk. The number of supported disks varies by VM size.

* HA systems use Premium page blobs as disks, with up to 8 TiB per page blob. The number of supported disks varies by VM size.

NOTE: You can purchase multiple node-based licenses for a Cloud Volumes ONTAP BYOL system to allocate more than 368 TiB of capacity. The number of licenses that you can purchase for a single node system or HA pair is unlimited. Be aware that disk limits can prevent you from reaching the capacity limit by using disks alone. You can go beyond the disk limit by https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html[tiering inactive data to object storage^]. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html[Learn how to add additional system licenses to Cloud Volumes ONTAP^].

=== Single node with a Premium license

[cols="14,20,31,33",width=68%,options="header"]
|===
| VM size
| Max data disks per node
| Max system capacity with disks alone
| Max system capacity with disks and data tiering

| DS5_v2 | 61 | 368 TiB | 368 TiB
| DS14_v2 | 61 | 368 TiB | 368 TiB
| DS15_v2 | 61 | 368 TiB | 368 TiB
| E32s_v3 | 29 | 368 TiB | 368 TiB
| E48s_v3 | 29 | 368 TiB | 368 TiB
| E64is_v3 | 29 | 368 TiB | 368 TiB
| E32ds_v4 | 29 | 368 TiB | 368 TiB
| E48ds_v4 | 29 | 368 TiB | 368 TiB
| E80ids_v4 | 61 | 368 TiB | 368 TiB
|===

=== Single node with node-based licensing

NOTE: For some VM types, you'll need several BYOL licenses to reach the max system capacity listed below. For example, you'd need 6 BYOL licenses to reach 1.95 PiB with DS5_v2.

[cols="10,18,18,18,18,18",width=100%,options="header"]
|===
| VM size
| Max data disks per node
2+| Max system capacity with one license
2+| Max system capacity with multiple licenses

2+| | *Disks alone* | *Disks + data tiering* | *Disks alone* | *Disks + data tiering*

| DS4_v2 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| DS5_v2 | 61 | 368 TiB | 368 TiB | 1.95 PiB | 368 TiB x each license
| DS13_v2 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| DS14_v2 | 61 | 368 TiB | 368 TiB | 1.95 PiB | 368 TiB x each license
| DS15_v2 | 61 | 368 TiB | 368 TiB | 1.95 PiB | 368 TiB x each license
| L8s_v2 | 13 | 368 TiB | 368 TiB | 416 TiB | 368 TiB x each license
| E4s_v3 | 5 | 160 TiB | 368 TiB | 160 TiB | 368 TiB x each license
| E8s_v3 | 13 | 368 TiB | 368 TiB | 416 TiB | 368 TiB x each license
| E32s_v3 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| E48s_v3 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| E64is_v3 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| E4ds_v4 | 5 | 160 TiB | 368 TiB | 160 TiB | 368 TiB x each license
| E8ds_v4 | 13 | 368 TiB | 368 TiB | 416 TiB | 368 TiB x each license
| E32ds_v4 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| E48ds_v4 | 29 | 368 TiB | 368 TiB | 928 TiB | 368 TiB x each license
| E80ids_v4 | 61 | 368 TiB | 368 TiB | 1.95 PiB | 368 TiB x each license
|===

=== Single node with capacity-based licensing

[cols="14,20,31,33",width=68%,options="header"]
|===
| VM size
| Max data disks per node
| Max system capacity with disks alone
| Max system capacity with disks and data tiering

| DS4_v2 | 29 | 928 TiB | 2 PiB
| DS5_v2 | 61 | 1.95 PiB | 2 PiB
| DS13_v2 | 29 | 928 TiB | 2 PiB
| DS14_v2 | 61 | 1.95 PiB | 2 PiB
| DS15_v2 | 61 | 1.95 PiB | 2 PiB
| L8s_v2 | 13 | 416 TiB | 2 PiB
| E4s_v3 | 5 | 160 TiB | 2 PiB
| E8s_v3 | 13 | 416 TiB | 2 PiB
| E32s_v3 | 29 | 928 TiB | 2 PiB
| E48s_v3 | 29 | 928 TiB | 2 PiB
| E64is_v3 | 29 | 928 TiB | 2 PiB
| E4ds_v4 | 5 | 160 TiB | 2 PiB
| E8ds_v4 | 13 | 416 TiB | 2 PiB
| E32ds_v4 | 29 | 928 TiB | 2 PiB
| E48ds_v4 | 29 | 928 TiB | 2 PiB
| E80ids_v4 | 61 | 1.95 PiB | 2 PiB

|===

=== HA pairs with a Premium license

[cols="14,20,31,33",width=68%,options="header"]
|===
| VM size
| Max data disks for an HA pair
| Max system capacity with disks alone
| Max system capacity with disks and data tiering

| DS5_v2 | 61 | 368 TiB | 368 TiB
| DS14_v2 | 61 | 368 TiB | 368 TiB
| DS15_v2 | 61 | 368 TiB | 368 TiB
| E8s_v3 | 13 | 104 TiB | 368 TiB
| E48s_v3 | 29 | 232 TiB | 368 TiB
| E32ds_v4 | 29 | 232 TiB | 368 TiB
| E48ds_v4 | 29 | 232 TiB | 368 TiB
| E80ids_v4 | 61 | 368 TiB | 368 TiB
|===

=== HA pairs with node-based licensing

[cols="10,18,18,18,18,18",width=100%,options="header"]
|===
| VM size
| Max data disks for an HA pair
2+| Max system capacity with one license
2+| Max system capacity with multiple licenses

2+| | *Disks alone* | *Disks + data tiering* | *Disks alone* | *Disks + data tiering*

| DS4_v2 | 29 | 232 TiB | 368 TiB | 232 TiB | 368 TiB x each license
| DS5_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 368 TiB x each license
| DS13_v2 | 29 | 232 TiB | 368 TiB | 232 TiB | 368 TiB x each license
| DS14_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 368 TiB x each license
| DS15_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 368 TiB x each license
| E8s_v3 | 13 | 104 TiB | 368 TiB | 104 TiB | 368 TiB x each license
| E48s_v3 | 29 | 232 TiB | 368 TiB | 232 TiB | 368 TiB x each license
| E8ds_v4 | 13 | 104 TiB | 368 TiB | 104 TiB | 368 TiB x each license
| E32ds_v4 | 29 | 232 TiB | 368 TiB | 232 TiB | 368 TiB x each license
| E48ds_v4 | 29 | 232 TiB | 368 TiB | 232 TiB | 368 TiB x each license
| E80ids_v4 | 61 | 368 TiB | 368 TiB | 488 TiB | 368 TiB x each license
|===

=== HA pairs with capacity-based licensing

[cols="14,20,31,33",width=68%,options="header"]
|===
| VM size
| Max data disks for an HA pair
| Max system capacity with disks alone
| Max system capacity with disks and data tiering

| DS4_v2 | 29 | 232 TiB | 2 PiB
| DS5_v2 | 61 | 488 TiB | 2 PiB
| DS13_v2 | 29 | 232 TiB | 2 PiB
| DS14_v2 | 61 | 488 TiB | 2 PiB
| DS15_v2 | 61 | 488 TiB | 2 PiB
| E8s_v3 | 13 | 104 TiB | 2 PiB
| E48s_v3 | 29 | 232 TiB | 2 PiB
| E8ds_v4 | 13 | 104 TiB | 2 PiB
| E32ds_v4 | 29 | 232 TiB | 2 PiB
| E48ds_v4 | 29 | 232 TiB | 2 PiB
| E80ids_v4 | 61 | 488 TiB | 2 PiB
|===

== Aggregate limits

Cloud Volumes ONTAP uses Azure storage as disks and groups them into _aggregates_. Aggregates provide storage to volumes.

[cols=2*,options="header,autowidth"]
|===
| Parameter
| Limit

| Maximum number of aggregates | Same as the disk limit
| Maximum aggregate size ^1^ |
384 TiB of raw capacity for single node ^2^
352 TiB of raw capacity for single node with PAYGO
96 TiB of raw capacity for HA pairs
| Disks per aggregate	| 1-12 ^3^
| Maximum number of RAID groups per aggregate	| 1
|===

Notes:

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

. If using node-based licensing, two BYOL licenses are required to reach 384 TiB.

. All disks in an aggregate must be the same size.

== Storage VM limits

Some configurations enable you to create additional storage VMs (SVMs) for Cloud Volumes ONTAP.

These are the tested limits. While it is theoretically possible to configure additional storage VMs, it's not supported.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html[Learn how to create additional storage VMs^].

[cols=2*,options="header,autowidth"]
|===
| License type
| Storage VM limit

| *Freemium* a|
24 storage VMs total ^1,2^

| *Capacity-based PAYGO or BYOL* ^3^ a|
24 storage VMs total ^1,2^

| *Node-based BYOL* ^4^ a|
24 storage VMs total ^1,2^

| *Node-based PAYGO* a|
* 1 storage VM for serving data
* 1 storage VM for disaster recovery

|===

. These 24 storage VMs can serve data or be configured for disaster recovery (DR).

. Each storage VM can have up to three LIFs where two are data LIFs and one is an SVM management LIF.

. For capacity-based licensing, there are no extra licensing costs for additional storage VMs, but there is a 4 TiB minimum capacity charge per storage VM. For example, if you create two storage VMs and each has 2 TiB of provisioned capacity, you'll be charged a total of 8 TiB.

. For node-based BYOL, an add-on license is required for each additional _data-serving_ storage VM beyond the first storage VM that comes with Cloud Volumes ONTAP by default. Contact your account team to obtain a storage VM add-on license.
+
Storage VMs that you configure for disaster recovery (DR) don't require an add-on license (they are free of charge), but they do count against the storage VM limit. For example, if you have 12 data-serving storage VMs and 12 storage VMs configured for disaster recovery, then you've reached the limit and can't create any additional storage VMs.

== File and volume limits

[cols="22,22,56",width=100%,options="header"]
|===
| Logical storage
| Parameter
| Limit

.2+| *Files*	| Maximum size | 16 TiB
| Maximum per volume |	Volume size dependent, up to 2 billion
| *FlexClone volumes*	| Hierarchical clone depth ^2^ | 499
.3+| *FlexVol volumes*	| Maximum per node |	500
| Minimum size |	20 MB
| Maximum size | 100 TiB
| *Qtrees* |	Maximum per FlexVol volume |	4,995
| *Snapshot copies* |	Maximum per FlexVol volume |	1,023

|===

Notes:

. Cloud Manager does not provide any setup or orchestration support for SVM disaster recovery. It also does not support storage-related tasks on an additional SVM. You must use System Manager or the CLI for SVM disaster recovery.
+
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856[SVM Disaster Recovery Preparation Express Guide^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857[SVM Disaster Recovery Express Guide^]

. Hierarchical clone depth is the maximum depth of a nested hierarchy of FlexClone volumes that can be created from a single FlexVol volume.

== iSCSI storage limits

[cols=3*,options="header,autowidth"]
|===
| iSCSI storage
| Parameter
| Limit

.4+| *LUNs*	| Maximum per node |	1,024
| Maximum number of LUN maps |	1,024
| Maximum size	| 16 TiB
| Maximum per volume	| 512
| *igroups*	| Maximum per node | 256
.2+| *Initiators*	| Maximum per node |	512
| Maximum per igroup	| 128
| *iSCSI sessions* |	Maximum per node | 1,024
.2+| *LIFs*	| Maximum per port |	32
| Maximum per portset	| 32
| *Portsets* |	Maximum per node |	256

|===
